# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_sponsers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsers',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
