# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_juvenileplayer_seniorplayer_veteranplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponser',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
