# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 07:21
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20170103_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponser',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '85x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
