# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_sponser_cropping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponser',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='sponser',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
