# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20170104_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('from_year', models.DateField()),
                ('to_year', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Histories',
            },
        ),
        migrations.AlterModelOptions(
            name='juvenileplayer',
            options={'verbose_name': 'Juvenile Player', 'verbose_name_plural': 'Juvenile Players'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['published_date'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='sponser',
            options={'ordering': ['-created'], 'verbose_name': 'Sponser', 'verbose_name_plural': 'Sponsers'},
        ),
        migrations.AlterModelOptions(
            name='veteranplayer',
            options={'verbose_name': 'Veteran Player', 'verbose_name_plural': 'Veteran Players'},
        ),
    ]
