# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20170109_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='from_year',
            field=models.DateField(help_text='please use numbers: mm/dd/yyyy'),
        ),
        migrations.AlterField(
            model_name='history',
            name='to_year',
            field=models.DateField(help_text='please use numbers: mm/dd/yyyy'),
        ),
    ]
