# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20170109_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email_address', models.EmailField(max_length=255, verbose_name='Email Address')),
                ('mobile', models.IntegerField(verbose_name='Phone Number')),
                ('birthday', models.DateField(verbose_name='Date of Birth')),
                ('house_number', models.CharField(blank=True, max_length=255, verbose_name='House Name/No')),
                ('address_one', models.CharField(max_length=255, verbose_name='Address One')),
                ('address_two', models.CharField(max_length=255, verbose_name='Adress Two')),
                ('town_city', models.CharField(max_length=255, verbose_name='Town or City')),
                ('postcode', models.IntegerField(default=10101, verbose_name='Postcode')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('priority_deposit', models.CharField(max_length=255, verbose_name='Priority Deposit')),
                ('number_of_seats', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
