# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='birthday',
            field=models.DateField(help_text='format: yyyy-dd-mm', verbose_name='Date of Birth'),
        ),
    ]
