# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_history_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='img',
            field=models.ImageField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='juvenileplayer',
            name='img',
            field=models.ImageField(blank=True, upload_to='player_img%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='seniorplayer',
            name='img',
            field=models.ImageField(blank=True, upload_to='player_img%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='veteranplayer',
            name='img',
            field=models.ImageField(blank=True, upload_to='player_img%Y-%m-%d'),
        ),
    ]
