# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20170109_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='summary',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
