# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_history_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='img',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='history',
            name='summary',
            field=models.CharField(help_text='300 characters for the summary filed.', max_length=300),
        ),
        migrations.AlterField(
            model_name='history',
            name='to_year',
            field=models.DateField(help_text='please use numbers: mm/dd/yyyy', null=True),
        ),
    ]
