# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20170111_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='address_one',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='address_two',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='house_number',
        ),
        migrations.AddField(
            model_name='ticket',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Home Address Adress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email_address',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
    ]
