# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20170111_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Home Address'),
        ),
    ]
