# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20170111_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_summary',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
